site_name: EUDI Wallet
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
  icon:
    logo: material/library-shelves 

markdown_extensions:
  - footnotes
  - sane_lists
  - tables
repo_url: https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework
repo_name: eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework

nav:
  - EUDI Wallet: index.md
  - Architecture and reference framework: architecture-and-reference-framework-main.md
  - Discussion topics: discussion-topics

extra:
  version:
    provider: mike

plugins:
  - mike
  - tags
