site_name: European Digital Identity
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.integrate
    - toc.follow
  logo: media/logo_eudi_white.svg
  favicon: media/favicon.ico

extra_css:
  - media/extra.css

markdown_extensions:
  - footnotes
  - sane_lists
  - tables

site_url: https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework
repo_url: https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework
repo_name: eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework

nav:
  - European Digital Identity Wallet: index.md
  - Architecture and reference framework: architecture-and-reference-framework-main.md
  - Discussion topics: discussion-topics/README.md
  - Technical specifications: technical-specifications/README.md
  - Reference Implementation: https://docs.eudi.dev/latest/

extra:
  version:
    provider: mike
    alias: true

plugins:
  - mike
  - tags
  - privacy
  - social
